import hdate, datetime
from zoneinfo import ZoneInfo
from ics import Calendar, Event
from location import latitude, longitude, timezone, altitude, diaspora, language
from statistics import median

def get_medianPlag(tod, c):
    #get date of previous Sunday. Returns today if it is Sunday
    tod = tod - datetime.timedelta(days = (tod.weekday() + 1) % 7)
    response_variable = {"day": tod}
    times = []
    for i in range(5):
        day = tod + datetime.timedelta(days = i)
        z = hdate.Zmanim(date = day, location = c, language = language, candle_lighting_offset = 18, havdalah_offset = 50).plag_hamincha.local.time()
        times.append(z)
    median_plag = median(times)
    response_variable["time"] = median_plag
    return response_variable

def get_mincha_time(t):
    t = datetime.datetime.combine(t['day'], t['time'])
    delta = t.minute % 5
    t = t.replace(second = 0) - datetime.timedelta(minutes = 10 + delta)
    return t

c = hdate.Location(name = "home", latitude = latitude, longitude = longitude, timezone = timezone, altitude = altitude, diaspora = diaspora)
tod = datetime.date.today()
h = hdate.HDateInfo(tod, diaspora= diaspora, language = language)
cal = Calendar()
years = 1
for i in range(years):
    rh = hdate.HebrewDate(h.hdate.year, hdate.Months.TISHREI, 1)
    gdate = rh.to_gdate()
    currentShabbos = hdate.HDateInfo(gdate, diaspora= diaspora, language = language).upcoming_shabbat
    weeks = h.hdate.year_size(h.hdate.year) // 7
    for j in range(weeks + 1):
        day = currentShabbos.gdate
        p = get_medianPlag(day, c)
        m = get_mincha_time(p)
        #set this to 1 to only print Sundays
        #set this to 5 to print Sunday-Thursday
        number_of_days = 5
        for k in range(number_of_days):
            day = (m + datetime.timedelta(days = k)).replace(tzinfo = ZoneInfo(timezone))
            e = Event()
            e.name = f'Plag Mincha/Maariv'
            e.begin = day
            e.end = day + datetime.timedelta( minutes = 30)
            e.transparent = True
            e.description = "Generated by https://github.com/Stromboli94/CandleLighting"
            cal.events.add(e)
        currentShabbos = currentShabbos.next_day.upcoming_shabbat
    h.hdate = h.hdate.replace(year = h.hdate.year + 1)

with open("MinchaTimes.ics", 'w') as f:
    f.writelines(cal.serialize_iter())

events = sorted(cal.events, key=lambda x: x.begin)
with open('MinchaTimes.txt', 'w') as f:
    for e in events:
        f.write(f'{e.name} - {e.begin.strftime("%D - %I:%M %p")}\n')
        print(f'{e.name} - {e.begin.strftime("%D - %I:%M %p")}')
