import hdate, datetime
from zoneinfo import ZoneInfo
from ics import Calendar, Event
from location import latitude, longitude, timezone, altitude, diaspora, hebrew
from statistics import median

def get_medianPlag(tod, c):
    #get date of previous Sunday. Returns today if it is Sunday
    tod = tod - datetime.timedelta(days = (tod.weekday() + 1) % 7)
    response_variable = {"day": tod}
    times = []
    for i in range(5):
        day = tod + datetime.timedelta(days = i)
        z = hdate.Zmanim(date = day, location = c, hebrew = False).zmanim["plag_mincha"].time()
        times.append(z)
    median_plag = median(times)
    response_variable["time"] = median_plag
    return response_variable

def get_mincha_time(t):
    t = datetime.datetime.combine(t['day'], t['time'])
    delta = t.minute % 5
    t = t.replace(second = 0) - datetime.timedelta(minutes = 10 + delta)
    return t

c = hdate.Location(name = "home", latitude = latitude, longitude = longitude, timezone = timezone, altitude = altitude, diaspora = diaspora)
tod = datetime.date.today()
h = hdate.HDate(tod, diaspora= diaspora, hebrew=hebrew)
cal = Calendar()
years = 1
for i in range(years):
    hols = h.get_holidays_for_year(types=[hdate.HolidayTypes.EREV_YOM_TOV, hdate.HolidayTypes.YOM_TOV])
    rh = hols[1][1]
    currentShabbos = rh.upcoming_shabbat
    weeks = h.year_size() // 7
    for j in range(weeks + 1):
        day = currentShabbos.gdate
        p = get_medianPlag(day, c)
        m = get_mincha_time(p)
        #set this to 1 to only print Sundays
        for k in range(5):
            day = (m + datetime.timedelta(days = k)).replace(tzinfo = ZoneInfo(timezone))
            heb = hdate.HDate(gdate = day.date() , diaspora = diaspora, hebrew = hebrew)
            if not heb.holiday_type in [hdate.HolidayTypes.EREV_YOM_TOV, hdate.HolidayTypes.YOM_TOV]:
                e = Event()
                e.name = f'Plag Mincha/Maariv'
                e.begin = day
                e.end = day + datetime.timedelta( minutes = 30)
                e.transparent = True
                e.description = "Generated by https://github.com/Stromboli94/CandleLighting"
                cal.events.add(e)
        currentShabbos = currentShabbos.next_day.upcoming_shabbat
    h.hdate.year += 1

with open("MinchaTimes.ics", 'w') as f:
    f.writelines(cal.serialize_iter())

events = sorted(cal.events, key=lambda x: x.begin)
with open('MinchaTimes.txt', 'w') as f:
    for e in events:
        f.write(f'{e.name} - {e.begin.strftime("%D - %#I:%M %p")}\n')
        print(f'{e.name} - {e.begin.strftime("%D - %#I:%M %p")}')
